log_file: logs/train.log
data:
  rgb:
    train_data: data/rgb_train.hdf5
    validation_data: data/rgb_validation.hdf5
  brdf:
    train_data: data/brdf_train.hdf5
    validation_data: data/brdf_validation.hdf5
  depth:
    train_data: data/depth_train.hdf5
    validation_data: data/depth_validation.hdf5
train:
  epochs: 30
  render:
    checkpoint_file_format: 'data/model/render_{epoch:02d}_{val_loss:.5f}.hdf5'
    output_file: data/model/render.hdf5
  depth:
    checkpoint_file_format: 'data/model/depth_{epoch:02d}_{val_loss:.5f}.hdf5'
    output_file: data/model/depth.hdf5

